### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by HackFisher** [bitsuperlab/web_play#34]
```
FreeLand:web_play fisher$ sudo npm install -g
Password:

> js2coffee@0.3.3 preinstall /usr/local/lib/node_modules/bitshares-play-gui/node_modules/lineman/node_modules/js2coffee
> node ./cyclic.js


> ws@0.5.0 install /usr/local/lib/node_modules/bitshares-play-gui/node_modules/lineman/node_modules/testem/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> ws@0.4.31 install /usr/local/lib/node_modules/bitshares-play-gui/node_modules/lineman/node_modules/testem/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm ERR! Error: shasum check failed for /tmp/npm-49490-qwnqfQzv/registry.npmjs.org/jshint/-/jshint-2.6.3.tgz
npm ERR! Expected: 84b470b8e5d5cd7adf0a3bd4975250443c9d311a
npm ERR! Actual:   09862c3e850aff6b10d60828053eefd09626684c
npm ERR! From:     https://registry.npmjs.org/jshint/-/jshint-2.6.3.tgz
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:943:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g"
npm ERR! cwd /Users/fisher/tmp/web_play
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/fisher/tmp/web_play/npm-debug.log
npm ERR! not ok code 0
```

**Comment by AlexChien** [comment]
Some reported that this checksum failed is due to unstable node/npm version.

You can try upgrading node and npm first

`brew upgrade node`
`npm install -g npm@latest`

and try to run the command again, if it's not solved, read on.

I have encounted the same issue before, but it seemed that it's because the downloaded package was partially transmitted.  I solved it by manually downloaded the package and install it locally.

you can do this

`wget https://registry.npmjs.org/jshint/-/jshint-2.6.3.tgz && npm install jshint-2.6.3.tgz`

or

`npm install https://registry.npmjs.org/jshint/-/jshint-2.6.3.tgz`
